# Generated by Django 3.0.5 on 2020-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCBILL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILLNO', models.CharField(max_length=200)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('COMPANYNAME', models.CharField(max_length=200)),
                ('PHONENO', models.CharField(max_length=200)),
                ('GSTNO', models.CharField(max_length=200)),
                ('NO_OXYEN_CYL', models.CharField(max_length=200)),
                ('NO_NIT_CYL', models.CharField(max_length=200)),
                ('NO_NIT_PURE', models.CharField(max_length=200)),
                ('NO_ARGON_CYL', models.CharField(max_length=200)),
                ('NO_DA_CYL', models.CharField(max_length=200)),
                ('NO_LPG_CYL', models.CharField(max_length=200)),
                ('NO_HYD_CYL', models.CharField(max_length=200)),
                ('NO_CO2_CYL', models.CharField(max_length=200)),
                ('NO_AMMO_CYL', models.CharField(max_length=200)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GSTBILL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILLNO', models.CharField(max_length=200)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('COMPANYNAME', models.CharField(max_length=200)),
                ('PHONENO', models.CharField(max_length=200)),
                ('GSTNO', models.CharField(max_length=200)),
                ('NO_OXYEN_CYL', models.CharField(max_length=200)),
                ('NO_NIT_CYL', models.CharField(max_length=200)),
                ('NO_NIT_PURE', models.CharField(max_length=200)),
                ('NO_ARGON_CYL', models.CharField(max_length=200)),
                ('NO_DA_CYL', models.CharField(max_length=200)),
                ('NO_LPG_CYL', models.CharField(max_length=200)),
                ('NO_HYD_CYL', models.CharField(max_length=200)),
                ('NO_CO2_CYL', models.CharField(max_length=200)),
                ('NO_AMMO_CYL', models.CharField(max_length=200)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NORMALBILL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILLNO', models.CharField(max_length=200)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('COMPANYNAME', models.CharField(max_length=200)),
                ('PHONENO', models.CharField(max_length=200)),
                ('GSTNO', models.CharField(max_length=200)),
                ('NO_OXYEN_CYL', models.CharField(max_length=200)),
                ('NO_NIT_CYL', models.CharField(max_length=200)),
                ('NO_NIT_PURE', models.CharField(max_length=200)),
                ('NO_ARGON_CYL', models.CharField(max_length=200)),
                ('NO_DA_CYL', models.CharField(max_length=200)),
                ('NO_LPG_CYL', models.CharField(max_length=200)),
                ('NO_HYD_CYL', models.CharField(max_length=200)),
                ('NO_CO2_CYL', models.CharField(max_length=200)),
                ('NO_AMMO_CYL', models.CharField(max_length=200)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
            ],
        ),
    ]
