# Generated by Django 3.0.8 on 2020-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200820_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
