# Generated by Django 3.1 on 2020-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('DOMAIN', models.CharField(max_length=50)),
                ('EXPERIENCE', models.IntegerField()),
                ('BRANCH', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=50)),
                ('GENDER', models.CharField(max_length=50)),
                ('SALARY', models.FloatField()),
            ],
            options={
                'verbose_name': 'TrainerInfo',
                'verbose_name_plural': 'TrainerInfos',
            },
        ),
    ]
